name: reusable workflow
on: 
   workflow_call:
     inputs:
        artifact-name:
            description: The name of the deployable artifact files.
            required: false
            default: dist
            type: string
jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
            - name: get-code
              uses: actions/download-artifact@v3
              with:
                name: ${{ inputs.artifact-name }}
            - name: List file
              run: ls
            - name: Output Information
              run: echo "Deploying and Uploading..."
